const express = require('express');
const router = express.Router();

const destinations = [
  {
    id: 1,
    name: "Taj Mahal",
    country: "India",
    attractions: ["Taj Mahal", "Agra Fort"],
  },
  {
    id: 2,
    name: "Jaipur",
    country: "India",
    attractions: ["Hawa Mahal", "Amber Fort"],
  },
  {
    id: 3,
    name: "Goa",
    country: "India",
    attractions: ["Baga Beach", "Basilica of Bom Jesus"],
  },
  {
    id: 4,
    name: "Kerala",
    country: "India",
    attractions: ["Backwaters", "Munnar"],
  },
  {
    id: 5,
    name: "Mumbai",
    country: "India",
    attractions: ["Gateway of India", "Marine Drive"],
  },
  {
    id: 6,
    name: "Delhi",
    country: "India",
    attractions: ["Red Fort", "Qutub Minar"],
  },
  {
    id: 7,
    name: "Varanasi",
    country: "India",
    attractions: ["Ganges River", "Kashi Vishwanath Temple"],
  },
  {
    id: 8,
    name: "Rajasthan",
    country: "India",
    attractions: ["Jaisalmer Fort", "City Palace"],
  },
  {
    id: 9,
    name: "Kolkata",
    country: "India",
    attractions: ["Victoria Memorial", "Howrah Bridge"],
  },
  {
    id: 10,
    name: "Chennai",
    country: "India",
    attractions: ["Marina Beach", "Fort St. George"],
  },
  {
    id: 11,
    name: "Agra",
    country: "India",
    attractions: ["Fatehpur Sikri", "Mehtab Bagh"],
  },
  {
    id: 12,
    name: "Amritsar",
    country: "India",
    attractions: ["Golden Temple", "Jallianwala Bagh"],
  },
  {
    id: 13,
    name: "Ahmedabad",
    country: "India",
    attractions: ["Sabarmati Ashram", "Kankaria Lake"],
  },
  {
    id: 14,
    name: "Bangalore",
    country: "India",
    attractions: ["Lal Bagh", "Bangalore Palace"],
  },
  {
    id: 15,
    name: "Hyderabad",
    country: "India",
    attractions: ["Charminar", "Golconda Fort"],
  },
  {
    id: 16,
    name: "Pune",
    country: "India",
    attractions: ["Shaniwar Wada", "Aga Khan Palace"],
  },
  {
    id: 17,
    name: "Chandigarh",
    country: "India",
    attractions: ["Rock Garden", "Sukhna Lake"],
  },
  {
    id: 18,
    name: "Shimla",
    country: "India",
    attractions: ["The Ridge", "Mall Road"],
  },
  {
    id: 19,
    name: "Manali",
    country: "India",
    attractions: ["Rohtang Pass", "Solang Valley"],
  },
  {
    id: 20,
    name: "Dharamshala",
    country: "India",
    attractions: ["McLeod Ganj", "HPCA Stadium"],
  },
  {
    id: 21,
    name: "Leh",
    country: "India",
    attractions: ["Pangong Lake", "Thiksey Monastery"],
  },
  {
    id: 22,
    name: "Srinagar",
    country: "India",
    attractions: ["Dal Lake", "Mughal Gardens"],
  },
  {
    id: 23,
    name: "Gulmarg",
    country: "India",
    attractions: ["Gulmarg Gondola", "Apharwat Peak"],
  },
  {
    id: 24,
    name: "Coorg",
    country: "India",
    attractions: ["Abbey Falls", "Raja's Seat"],
  },
  {
    id: 25,
    name: "Ooty",
    country: "India",
    attractions: ["Ooty Lake", "Botanical Gardens"],
  },
  {
    id: 26,
    name: "Mysore",
    country: "India",
    attractions: ["Mysore Palace", "Chamundi Hills"],
  },
  {
    id: 27,
    name: "Rishikesh",
    country: "India",
    attractions: ["Lakshman Jhula", "Triveni Ghat"],
  },
  {
    id: 28,
    name: "Haridwar",
    country: "India",
    attractions: ["Har Ki Pauri", "Chandi Devi Temple"],
  },
  {
    id: 29,
    name: "Dehradun",
    country: "India",
    attractions: ["Robber's Cave", "Sahastradhara"],
  },
  {
    id: 30,
    name: "Nainital",
    country: "India",
    attractions: ["Naini Lake", "Tiffin Top"],
  },
  {
    id: 31,
    name: "Mussoorie",
    country: "India",
    attractions: ["Kempty Falls", "Lal Tibba"],
  },
  {
    id: 32,
    name: "Jim Corbett",
    country: "India",
    attractions: ["Corbett National Park", "Dhikala"],
  },
  {
    id: 33,
    name: "Ranikhet",
    country: "India",
    attractions: ["Chaubatia Gardens", "Jhula Devi Temple"],
  },
  {
    id: 34,
    name: "Mount Abu",
    country: "India",
    attractions: ["Nakki Lake", "Dilwara Temples"],
  },
  {
    id: 35,
    name: "Udaipur",
    country: "India",
    attractions: ["City Palace", "Lake Pichola"],
  },
  {
    id: 36,
    name: "Jodhpur",
    country: "India",
    attractions: ["Mehrangarh Fort", "Umaid Bhawan Palace"],
  },
  {
    id: 37,
    name: "Pushkar",
    country: "India",
    attractions: ["Pushkar Lake", "Brahma Temple"],
  },
  {
    id: 38,
    name: "Ajmer",
    country: "India",
    attractions: ["Ajmer Sharif Dargah", "Ana Sagar Lake"],
  },
  {
    id: 39,
    name: "Bikaner",
    country: "India",
    attractions: ["Junagarh Fort", "Karni Mata Temple"],
  },
  {
    id: 40,
    name: "Kota",
    country: "India",
    attractions: ["Seven Wonders Park", "Kota Barrage"],
  },
  {
    id: 41,
    name: "Jaisalmer",
    country: "India",
    attractions: ["Jaisalmer Fort", "Sam Sand Dunes"],
  },
  {
    id: 42,
    name: "Alleppey",
    country: "India",
    attractions: ["Alleppey Backwaters", "Marari Beach"],
  },
  {
    id: 43,
    name: "Kochi",
    country: "India",
    attractions: ["Fort Kochi", "Mattancherry Palace"],
  },
  {
    id: 44,
    name: "Trivandrum",
    country: "India",
    attractions: ["Padmanabhaswamy Temple", "Kovalam Beach"],
  },
  {
    id: 45,
    name: "Munnar",
    country: "India",
    attractions: ["Eravikulam National Park", "Tea Gardens"],
  },
  {
    id: 46,
    name: "Thekkady",
    country: "India",
    attractions: ["Periyar Wildlife Sanctuary", "Spice Plantations"],
  },
  {
    id: 47,
    name: "Kumarakom",
    country: "India",
    attractions: ["Vembanad Lake", "Bird Sanctuary"],
  },
  {
    id: 48,
    name: "Kovalam",
    country: "India",
    attractions: ["Lighthouse Beach", "Hawah Beach"],
  },
  {
    id: 49,
    name: "Thrissur",
    country: "India",
    attractions: ["Vadakkunnathan Temple", "Athirappilly Falls"],
  },
  {
    id: 50,
    name: "Wayanad",
    country: "India",
    attractions: ["Edakkal Caves", "Banasura Sagar Dam"],
  },
  {
    id: 51,
    name: "Kozhikode",
    country: "India",
    attractions: ["Kappad Beach", "Mananchira Square"],
  },
  {
    id: 52,
    name: "Varkala",
    country: "India",
    attractions: ["Varkala Beach", "Sivagiri Mutt"],
  },
  {
    id: 53,
    name: "Kannur",
    country: "India",
    attractions: ["Payyambalam Beach", "St. Angelo Fort"],
  },
  {
    id: 54,
    name: "Bekal",
    country: "India",
    attractions: ["Bekal Fort", "Bekal Beach"],
  },
  {
    id: 55,
    name: "Madurai",
    country: "India",
    attractions: ["Meenakshi Temple", "Thirumalai Nayakkar Mahal"],
  },
  {
    id: 56,
    name: "Tiruchirapalli",
    country: "India",
    attractions: ["Rockfort Temple", "Srirangam Temple"],
  },
  {
    id: 57,
    name: "Rameswaram",
    country: "India",
    attractions: ["Ramanathaswamy Temple", "Pamban Bridge"],
  },
  {
    id: 58,
    name: "Kanyakumari",
    country: "India",
    attractions: ["Vivekananda Rock Memorial", "Thiruvalluvar Statue"],
  },
  {
    id: 59,
    name: "Coimbatore",
    country: "India",
    attractions: ["Marudhamalai Temple", "VOC Park"],
  },
  {
    id: 60,
    name: "Salem",
    country: "India",
    attractions: ["Yercaud", "1008 Lingam Temple"],
  },
  {
    id: 61,
    name: "Vellore",
    country: "India",
    attractions: ["Vellore Fort", "Golden Temple"],
  },
  {
    id: 62,
    name: "Thanjavur",
    country: "India",
    attractions: ["Brihadeeswarar Temple", "Thanjavur Palace"],
  },
  {
    id: 63,
    name: "Kanchipuram",
    country: "India",
    attractions: ["Kailasanathar Temple", "Ekambareswarar Temple"],
  },
  {
    id: 64,
    name: "Tirupati",
    country: "India",
    attractions: [
      "Tirumala Venkateswara Temple",
      "Sri Kapileswaraswami Temple",
    ],
  },
  {
    id: 65,
    name: "Hampi",
    country: "India",
    attractions: ["Virupaksha Temple", "Vittala Temple"],
  },
  {
    id: 66,
    name: "Badami",
    country: "India",
    attractions: ["Badami Caves", "Banashankari Temple"],
  },
  {
    id: 67,
    name: "Bijapur",
    country: "India",
    attractions: ["Gol Gumbaz", "Ibrahim Rauza"],
  },
  {
    id: 68,
    name: "Gokarna",
    country: "India",
    attractions: ["Om Beach", "Mahabaleshwar Temple"],
  },
  {
    id: 69,
    name: "Pondicherry",
    country: "India",
    attractions: ["Promenade Beach", "Auroville"],
  },
  {
    id: 70,
    name: "Mahabalipuram",
    country: "India",
    attractions: ["Shore Temple", "Pancha Rathas"],
  },
  {
    id: 71,
    name: "Kodaikanal",
    country: "India",
    attractions: ["Kodai Lake", "Coaker's Walk"],
  },
  {
    id: 72,
    name: "Yercaud",
    country: "India",
    attractions: ["Yercaud Lake", "Shevaroy Hills"],
  },
  {
    id: 73,
    name: "Vishakhapatnam",
    country: "India",
    attractions: ["Rishikonda Beach", "Kailasagiri"],
  },
  {
    id: 74,
    name: "Araku Valley",
    country: "India",
    attractions: ["Borra Caves", "Katiki Waterfalls"],
  },
  {
    id: 75,
    name: "Warangal",
    country: "India",
    attractions: ["Warangal Fort", "Thousand Pillar Temple"],
  },
  {
    id: 76,
    name: "Nagpur",
    country: "India",
    attractions: ["Deekshabhoomi", "Futala Lake"],
  },
  {
    id: 77,
    name: "Aurangabad",
    country: "India",
    attractions: ["Ajanta Caves", "Ellora Caves"],
  },
  {
    id: 78,
    name: "Nashik",
    country: "India",
    attractions: ["Trimbakeshwar Temple", "Sula Vineyards"],
  },
  {
    id: 79,
    name: "Shirdi",
    country: "India",
    attractions: ["Sai Baba Temple", "Dwarkamai"],
  },
  {
    id: 80,
    name: "Lonavala",
    country: "India",
    attractions: ["Tiger's Leap", "Bhaja Caves"],
  },
  {
    id: 81,
    name: "Mahabaleshwar",
    country: "India",
    attractions: ["Venna Lake", "Pratapgad Fort"],
  },
  {
    id: 82,
    name: "Alibaug",
    country: "India",
    attractions: ["Alibaug Beach", "Kolaba Fort"],
  },
  {
    id: 83,
    name: "Kolhapur",
    country: "India",
    attractions: ["Mahalakshmi Temple", "Panhala Fort"],
  },
  {
    id: 84,
    name: "Ratnagiri",
    country: "India",
    attractions: ["Ganapatipule", "Ratnadurg Fort"],
  },
  {
    id: 85,
    name: "Sindhudurg",
    country: "India",
    attractions: ["Sindhudurg Fort", "Tarkarli Beach"],
  },
  {
    id: 86,
    name: "Puri",
    country: "India",
    attractions: ["Jagannath Temple", "Puri Beach"],
  },
  {
    id: 87,
    name: "Bhubaneswar",
    country: "India",
    attractions: ["Lingaraj Temple", "Nandankanan Zoo"],
  },
  {
    id: 88,
    name: "Konark",
    country: "India",
    attractions: ["Sun Temple", "Chandrabhaga Beach"],
  },
  {
    id: 89,
    name: "Cuttack",
    country: "India",
    attractions: ["Barabati Fort", "Dhabaleswar Island"],
  },
  {
    id: 90,
    name: "Sambalpur",
    country: "India",
    attractions: ["Hirakud Dam", "Samaleswari Temple"],
  },
  {
    id: 91,
    name: "Rourkela",
    country: "India",
    attractions: ["Hanuman Vatika", "Vedavyas Temple"],
  },
  {
    id: 92,
    name: "Gwalior",
    country: "India",
    attractions: ["Gwalior Fort", "Saas Bahu Temple"],
  },
  {
    id: 93,
    name: "Khajuraho",
    country: "India",
    attractions: ["Khajuraho Temples", "Panna National Park"],
  },
  {
    id: 94,
    name: "Orchha",
    country: "India",
    attractions: ["Orchha Fort", "Jehangir Mahal"],
  },
  {
    id: 95,
    name: "Ujjain",
    country: "India",
    attractions: ["Mahakaleshwar Temple", "Kumbh Mela"],
  },
  {
    id: 96,
    name: "Indore",
    country: "India",
    attractions: ["Rajwada", "Lal Bagh Palace"],
  },
  {
    id: 97,
    name: "Bhopal",
    country: "India",
    attractions: ["Sanchi Stupa", "Bhojpur Temple"],
  },
  {
    id: 98,
    name: "Jabalpur",
    country: "India",
    attractions: ["Dhuandhar Falls", "Marble Rocks"],
  },
  {
    id: 99,
    name: "Bandhavgarh",
    country: "India",
    attractions: ["Bandhavgarh National Park", "Bandhavgarh Fort"],
  },
  {
    id: 100,
    name: "Kanha",
    country: "India",
    attractions: ["Kanha National Park", "Bamni Dadar"],
  },

  // Adding more destinations to reach 500
  {
    id: 101,
    name: "Shivanasamudra",
    country: "India",
    attractions: ["Shivanasamudra Falls"],
  },
  {
    id: 102,
    name: "Hassan",
    country: "India",
    attractions: ["Belur", "Halebidu"],
  },
  {
    id: 103,
    name: "Chikmagalur",
    country: "India",
    attractions: ["Mullayanagiri", "Baba Budangiri"],
  },
  {
    id: 104,
    name: "Hampi",
    country: "India",
    attractions: ["Vijaya Vittala Temple", "Hemakuta Hill"],
  },
  {
    id: 105,
    name: "Bijapur",
    country: "India",
    attractions: ["Gol Gumbaz", "Ibrahim Rauza"],
  },
  {
    id: 106,
    name: "Badami",
    country: "India",
    attractions: ["Badami Caves", "Banashankari Temple"],
  },
  {
    id: 107,
    name: "Pattadakal",
    country: "India",
    attractions: ["Group of Monuments at Pattadakal"],
  },
  {
    id: 108,
    name: "Aihole",
    country: "India",
    attractions: ["Durga Temple", "Group of Temples"],
  },
  {
    id: 109,
    name: "Bidar",
    country: "India",
    attractions: ["Bidar Fort", "Bahmani Tombs"],
  },
  {
    id: 110,
    name: "Gulbarga",
    country: "India",
    attractions: ["Gulbarga Fort", "Jama Masjid"],
  },
  {
    id: 111,
    name: "Hubli",
    country: "India",
    attractions: ["Nrupatunga Hill", "Unkal Lake"],
  },
  {
    id: 112,
    name: "Dandeli",
    country: "India",
    attractions: ["Dandeli Wildlife Sanctuary", "River Rafting"],
  },
  {
    id: 113,
    name: "Gokarna",
    country: "India",
    attractions: ["Om Beach", "Mahabaleshwar Temple"],
  },
  {
    id: 114,
    name: "Murudeshwar",
    country: "India",
    attractions: ["Murudeshwar Temple", "Murudeshwar Beach"],
  },
  {
    id: 115,
    name: "Karwar",
    country: "India",
    attractions: ["Karwar Beach", "Sadashivgad Fort"],
  },
  {
    id: 116,
    name: "Mangalore",
    country: "India",
    attractions: ["Panambur Beach", "Kadri Manjunath Temple"],
  },
  {
    id: 117,
    name: "Udupi",
    country: "India",
    attractions: ["Sri Krishna Temple", "Malpe Beach"],
  },
  {
    id: 118,
    name: "Manipal",
    country: "India",
    attractions: ["Manipal Lake", "End Point"],
  },
  {
    id: 119,
    name: "Gulbarga",
    country: "India",
    attractions: ["Gulbarga Fort", "Khwaja Bande Nawaz Dargah"],
  },
  {
    id: 120,
    name: "Belgaum",
    country: "India",
    attractions: ["Belgaum Fort", "Kapileshwar Temple"],
  },
  {
    id: 121,
    name: "Sakleshpur",
    country: "India",
    attractions: ["Manjarabad Fort", "Bisle Ghat"],
  },
  {
    id: 122,
    name: "Kumarakom",
    country: "India",
    attractions: ["Bird Sanctuary", "Backwaters"],
  },
  {
    id: 123,
    name: "Kollam",
    country: "India",
    attractions: ["Ashtamudi Lake", "Thangassery"],
  },
  {
    id: 124,
    name: "Kottayam",
    country: "India",
    attractions: ["Vembanad Lake", "Thirunakkara Mahadeva Temple"],
  },
  {
    id: 125,
    name: "Thrissur",
    country: "India",
    attractions: ["Athirappilly Waterfalls", "Vadakkunnathan Temple"],
  },
  {
    id: 126,
    name: "Palakkad",
    country: "India",
    attractions: ["Palakkad Fort", "Silent Valley National Park"],
  },
  {
    id: 127,
    name: "Wayanad",
    country: "India",
    attractions: ["Edakkal Caves", "Banasura Sagar Dam"],
  },
  {
    id: 128,
    name: "Malappuram",
    country: "India",
    attractions: ["Kottakkunnu", "Thirunavaya Temple"],
  },
  {
    id: 129,
    name: "Kannur",
    country: "India",
    attractions: ["Payyambalam Beach", "St. Angelo Fort"],
  },
  {
    id: 130,
    name: "Kasargod",
    country: "India",
    attractions: ["Bekal Fort", "Chandragiri Fort"],
  },
  {
    id: 131,
    name: "Alleppey",
    country: "India",
    attractions: ["Backwaters", "Marari Beach"],
  },
  {
    id: 132,
    name: "Kozhikode",
    country: "India",
    attractions: ["Kappad Beach", "Mananchira Square"],
  },
  {
    id: 133,
    name: "Pathanamthitta",
    country: "India",
    attractions: ["Sabarimala Temple", "Aranmula Temple"],
  },
  {
    id: 134,
    name: "Adoor",
    country: "India",
    attractions: ["Parthasarathy Temple", "Trichennamangalam Mahadeva Temple"],
  },
  {
    id: 135,
    name: "Guruvayur",
    country: "India",
    attractions: ["Guruvayur Temple", "Mammiyoor Temple"],
  },
  {
    id: 136,
    name: "Munnar",
    country: "India",
    attractions: ["Tea Gardens", "Eravikulam National Park"],
  },
  {
    id: 137,
    name: "Varkala",
    country: "India",
    attractions: ["Papanasam Beach", "Varkala Cliffs"],
  },
  {
    id: 138,
    name: "Vythiri",
    country: "India",
    attractions: ["Wayanad", "Pookode Lake"],
  },
  {
    id: 139,
    name: "Alappuzha",
    country: "India",
    attractions: ["Backwaters", "Alleppey Beach"],
  },
  {
    id: 140,
    name: "Ranthambore",
    country: "India",
    attractions: ["Ranthambore Fort", "Ranthambore National Park"],
  },
  {
    id: 141,
    name: "Tawang",
    country: "India",
    attractions: ["Tawang Monastery", "Sela Pass"],
  },
  {
    id: 142,
    name: "Ziro",
    country: "India",
    attractions: ["Ziro Valley", "Talle Valley"],
  },
  {
    id: 143,
    name: "Majuli",
    country: "India",
    attractions: ["River Island", "Satras"],
  },
  {
    id: 144,
    name: "Haflong",
    country: "India",
    attractions: ["Haflong Lake", "Maibang"],
  },
  {
    id: 145,
    name: "Sivasagar",
    country: "India",
    attractions: ["Sivasagar Lake", "Talatal Ghar"],
  },
  {
    id: 146,
    name: "Imphal",
    country: "India",
    attractions: ["Loktak Lake", "Kangla Fort"],
  },
  {
    id: 147,
    name: "Moirang",
    country: "India",
    attractions: ["INA Museum", "Keibul Lamjao National Park"],
  },
  {
    id: 148,
    name: "Shillong",
    country: "India",
    attractions: ["Umiam Lake", "Elephant Falls"],
  },
  {
    id: 149,
    name: "Cherrapunji",
    country: "India",
    attractions: ["Living Root Bridges", "Mawsmai Caves"],
  },
  {
    id: 150,
    name: "Mawlynnong",
    country: "India",
    attractions: ["Cleanest Village", "Living Root Bridge"],
  },
  {
    id: 151,
    name: "Jowai",
    country: "India",
    attractions: ["Nartiang Monoliths", "Thadlaskein Lake"],
  },
  {
    id: 152,
    name: "Aizawl",
    country: "India",
    attractions: ["Durtlang Hills", "Reiek"],
  },
  {
    id: 153,
    name: "Lunglei",
    country: "India",
    attractions: ["Thorangtlang Wildlife Sanctuary", "Lunglei Bridge"],
  },
  {
    id: 154,
    name: "Champhai",
    country: "India",
    attractions: ["Rih Dil", "Lianchhiari Lunglen Tlang"],
  },
  {
    id: 155,
    name: "Kohima",
    country: "India",
    attractions: ["Kohima War Cemetery", "Japfu Peak"],
  },
  {
    id: 156,
    name: "Dimapur",
    country: "India",
    attractions: ["Kachari Ruins", "Zoological Park"],
  },
  {
    id: 157,
    name: "Mon",
    country: "India",
    attractions: ["Konyak Village", "Veda Peak"],
  },
  {
    id: 158,
    name: "Phek",
    country: "India",
    attractions: ["Shilloi Lake", "Dzükou Valley"],
  },
  {
    id: 159,
    name: "Itanagar",
    country: "India",
    attractions: ["Itanagar Wildlife Sanctuary", "Ita Fort"],
  },
  {
    id: 160,
    name: "Pasighat",
    country: "India",
    attractions: ["Siang River", "Daying Ering Wildlife Sanctuary"],
  },
  {
    id: 161,
    name: "Tezpur",
    country: "India",
    attractions: ["Agnigarh", "Nameri National Park"],
  },
  {
    id: 162,
    name: "Guwahati",
    country: "India",
    attractions: ["Kamakhya Temple", "Umananda Temple"],
  },
  {
    id: 163,
    name: "Kaziranga",
    country: "India",
    attractions: ["Kaziranga National Park"],
  },
  {
    id: 164,
    name: "Jorhat",
    country: "India",
    attractions: ["Hoollongapar Gibbon Sanctuary", "Jorhat Gymkhana Club"],
  },
  {
    id: 165,
    name: "Majuli",
    country: "India",
    attractions: ["River Island", "Satras"],
  },
  {
    id: 166,
    name: "Sivasagar",
    country: "India",
    attractions: ["Sivasagar Lake", "Talatal Ghar"],
  },
  {
    id: 167,
    name: "Haflong",
    country: "India",
    attractions: ["Haflong Lake", "Maibang"],
  },
  {
    id: 168,
    name: "Digboi",
    country: "India",
    attractions: ["Digboi Oil Refinery", "Digboi War Cemetery"],
  },
  {
    id: 169,
    name: "Silchar",
    country: "India",
    attractions: ["Maniharan Tunnel", "Bhubaneswar Temple"],
  },
  {
    id: 170,
    name: "Dibrugarh",
    country: "India",
    attractions: ["Dibrugarh Tea Gardens", "Jokai Botanical Garden"],
  },
  {
    id: 171,
    name: "Tezpur",
    country: "India",
    attractions: ["Agnigarh", "Bamuni Hills"],
  },
  {
    id: 172,
    name: "Manas National Park",
    country: "India",
    attractions: ["Manas National Park"],
  },
  {
    id: 173,
    name: "Dibrugarh",
    country: "India",
    attractions: ["Radha Krishna Mandir", "Joypur Rainforest"],
  },
  {
    id: 174,
    name: "Sibsagar",
    country: "India",
    attractions: ["Rang Ghar", "Kareng Ghar"],
  },
  {
    id: 175,
    name: "Gaya",
    country: "India",
    attractions: ["Mahabodhi Temple", "Vishnupad Temple"],
  },
  {
    id: 176,
    name: "Nalanda",
    country: "India",
    attractions: ["Nalanda University Ruins", "Hiuen Tsang Memorial Hall"],
  },
  {
    id: 177,
    name: "Patna",
    country: "India",
    attractions: ["Golghar", "Patna Sahib Gurudwara"],
  },
  {
    id: 178,
    name: "Rajgir",
    country: "India",
    attractions: ["Vishwa Shanti Stupa", "Griddhakuta Peak"],
  },
  {
    id: 179,
    name: "Bodh Gaya",
    country: "India",
    attractions: ["Mahabodhi Temple", "Bodhi Tree"],
  },
  {
    id: 180,
    name: "Vaishali",
    country: "India",
    attractions: ["Ashoka Pillar", "Bawan Pokhar Temple"],
  },
  {
    id: 181,
    name: "Bhagalpur",
    country: "India",
    attractions: ["Vikramshila Gangetic Dolphin Sanctuary", "Kuppaghat"],
  },
  {
    id: 182,
    name: "Muzaffarpur",
    country: "India",
    attractions: ["Garib Sthan Mandir", "Baba Garibnath Temple"],
  },
  {
    id: 183,
    name: "Purnia",
    country: "India",
    attractions: ["Purnia Court", "Forbesganj"],
  },
  {
    id: 184,
    name: "Begusarai",
    country: "India",
    attractions: ["Kanwar Lake Bird Sanctuary", "Naina Devi Temple"],
  },
  {
    id: 185,
    name: "Darbhanga",
    country: "India",
    attractions: ["Ahilya Asthan", "Darbhanga Fort"],
  },
  {
    id: 186,
    name: "Madhubani",
    country: "India",
    attractions: ["Jhanjharpur", "Uchhaith Temple"],
  },
  {
    id: 187,
    name: "Samastipur",
    country: "India",
    attractions: ["Khudneshwar Asthan", "Mannipur Temple"],
  },
  {
    id: 188,
    name: "Sitamarhi",
    country: "India",
    attractions: ["Janki Temple", "Punaura Dham"],
  },
  {
    id: 189,
    name: "Motihari",
    country: "India",
    attractions: ["Motijheel", "Gandhi Sangrahalaya"],
  },
  {
    id: 190,
    name: "Chhapra",
    country: "India",
    attractions: ["Aami Temple", "Gautam Asthan"],
  },
  {
    id: 191,
    name: "Hajipur",
    country: "India",
    attractions: ["Bari Sangat", "Ramchaura Mandir"],
  },
  {
    id: 192,
    name: "Sheohar",
    country: "India",
    attractions: ["Hariharnath Temple", "Sitakund"],
  },
  {
    id: 193,
    name: "Araria",
    country: "India",
    attractions: ["Araria Jama Masjid", "Forbesganj"],
  },
  {
    id: 194,
    name: "Aurangabad",
    country: "India",
    attractions: ["Deo Sun Temple", "Umga"],
  },
  {
    id: 195,
    name: "Buxar",
    country: "India",
    attractions: ["Buxar Fort", "Ramrekha Ghat"],
  },
  {
    id: 196,
    name: "Gopalganj",
    country: "India",
    attractions: ["Thawe Temple", "Dighwa Dubauli"],
  },
  {
    id: 197,
    name: "Jehanabad",
    country: "India",
    attractions: ["Barabar Caves", "Bhimbandh Wildlife Sanctuary"],
  },
  {
    id: 198,
    name: "Jamui",
    country: "India",
    attractions: ["Simultalla Hill Station", "Kali Mandir"],
  },
  {
    id: 199,
    name: "Khagaria",
    country: "India",
    attractions: ["Naginabad", "Munger Ganga Bridge"],
  },
  {
    id: 200,
    name: "Lakhisarai",
    country: "India",
    attractions: ["Ashok Dham Temple", "Surya Mandir"],
  },
  {
    id: 201,
    name: "Madhepura",
    country: "India",
    attractions: ["Singheshwar Temple", "Ghormara Temple"],
  },
  {
    id: 202,
    name: "Munger",
    country: "India",
    attractions: ["Munger Fort", "Sita Kund"],
  },
  {
    id: 203,
    name: "Nawada",
    country: "India",
    attractions: ["Kakolat Waterfall", "Narad Museum"],
  },
  {
    id: 204,
    name: "Rupas",
    country: "India",
    attractions: ["Thorny Temple", "Sacred Lake"],
  },
  {
    id: 205,
    name: "Saharsa",
    country: "India",
    attractions: ["Matsyagandha Temple", "Madhepura"],
  },
  {
    id: 206,
    name: "Supaul",
    country: "India",
    attractions: ["Durga Sthan", "Rupani Bazar"],
  },
  {
    id: 207,
    name: "Gopalganj",
    country: "India",
    attractions: ["Thawe Temple", "Dighwa Dubauli"],
  },
  {
    id: 208,
    name: "Siwan",
    country: "India",
    attractions: ["Mehandar Temple", "Hussain Shaheed Mosque"],
  },
  {
    id: 209,
    name: "Kaimur",
    country: "India",
    attractions: ["Baijnath Temple", "Karkat Waterfall"],
  },
  {
    id: 210,
    name: "Ranchi",
    country: "India",
    attractions: ["Dassam Falls", "Ranchi Lake"],
  },
  {
    id: 211,
    name: "Jamshedpur",
    country: "India",
    attractions: ["Jubilee Park", "Tata Steel Zoological Park"],
  },
  {
    id: 212,
    name: "Dhanbad",
    country: "India",
    attractions: ["Maithon Dam", "Topchanchi Lake"],
  },
  {
    id: 213,
    name: "Bokaro",
    country: "India",
    attractions: ["Bokaro Steel Plant", "Garga Dam"],
  },
  {
    id: 214,
    name: "Deoghar",
    country: "India",
    attractions: ["Baidyanath Temple", "Trikuta Hills"],
  },
  {
    id: 215,
    name: "Hazaribagh",
    country: "India",
    attractions: ["Canary Hill", "Hazaribagh Lake"],
  },
  {
    id: 216,
    name: "Giridih",
    country: "India",
    attractions: ["Parasnath Hill", "Usri Falls"],
  },
  {
    id: 217,
    name: "Palamu",
    country: "India",
    attractions: ["Betla National Park", "Palamu Fort"],
  },
  {
    id: 218,
    name: "Godda",
    country: "India",
    attractions: ["Basantrai", "Ratneshwar Dham"],
  },
  {
    id: 219,
    name: "Lohardaga",
    country: "India",
    attractions: ["Panchghagh Falls", "Hirni Falls"],
  },
  {
    id: 220,
    name: "Simdega",
    country: "India",
    attractions: ["Ram Rekha Dham", "Kelaghgh Dam"],
  },
  {
    id: 221,
    name: "Pakur",
    country: "India",
    attractions: ["Nityakali Mandir", "Mahakali Mandir"],
  },
  {
    id: 222,
    name: "Dumka",
    country: "India",
    attractions: ["Malooti Temples", "Baba Basukinath Dham"],
  },
  {
    id: 223,
    name: "Garhwa",
    country: "India",
    attractions: ["Ranka Raj Palace", "Tundi Mahadev Mandir"],
  },
  {
    id: 224,
    name: "Koderma",
    country: "India",
    attractions: ["Koderma Reserve Forest", "Tilaiya Dam"],
  },
  {
    id: 225,
    name: "Latehar",
    country: "India",
    attractions: ["Lodh Falls", "Betla National Park"],
  },
  {
    id: 226,
    name: "Chatra",
    country: "India",
    attractions: ["Bhawani Shankar Temple", "Kolhua Hill"],
  },
  {
    id: 227,
    name: "Barmer",
    country: "India",
    attractions: ["Barmer Fort", "Kiradu Temples"],
  },
  {
    id: 228,
    name: "Baran",
    country: "India",
    attractions: ["Sitabari", "Shahabad Fort"],
  },
  {
    id: 229,
    name: "Banswara",
    country: "India",
    attractions: ["Mahi Dam", "Anand Sagar Lake"],
  },
  {
    id: 230,
    name: "Bundi",
    country: "India",
    attractions: ["Taragarh Fort", "Sukh Mahal"],
  },
  {
    id: 231,
    name: "Churu",
    country: "India",
    attractions: ["Churu Fort", "Tal Chappar Sanctuary"],
  },
  {
    id: 232,
    name: "Dausa",
    country: "India",
    attractions: ["Chand Baori", "Mehandipur Balaji Temple"],
  },
  {
    id: 233,
    name: "Dholpur",
    country: "India",
    attractions: ["Dholpur Palace", "Van Vihar Wildlife Sanctuary"],
  },
  {
    id: 234,
    name: "Dungarpur",
    country: "India",
    attractions: ["Juna Mahal", "Badal Mahal"],
  },
  {
    id: 235,
    name: "Hanumangarh",
    country: "India",
    attractions: ["Bhatner Fort", "Kalibangan Museum"],
  },
  {
    id: 236,
    name: "Jaisalmer",
    country: "India",
    attractions: ["Jaisalmer Fort", "Sam Sand Dunes"],
  },
  {
    id: 237,
    name: "Jhalawar",
    country: "India",
    attractions: ["Gagron Fort", "Jhalawar Fort"],
  },
  {
    id: 238,
    name: "Jhunjhunu",
    country: "India",
    attractions: ["Rani Sati Temple", "Mandawa Fort"],
  },
  {
    id: 239,
    name: "Karauli",
    country: "India",
    attractions: ["Karauli Fort", "Kaila Devi Temple"],
  },
  {
    id: 240,
    name: "Nagaur",
    country: "India",
    attractions: ["Nagaur Fort", "Jain Glass Temple"],
  },
  {
    id: 241,
    name: "Pali",
    country: "India",
    attractions: ["Ranakpur Jain Temple", "Bangur Museum"],
  },
  {
    id: 242,
    name: "Rajsamand",
    country: "India",
    attractions: ["Kumbhalgarh Fort", "Rajsamand Lake"],
  },
  {
    id: 243,
    name: "Sawai Madhopur",
    country: "India",
    attractions: ["Ranthambore Fort", "Ranthambore National Park"],
  },
  {
    id: 244,
    name: "Sikar",
    country: "India",
    attractions: ["Harshnath Temple", "Laxmangarh Fort"],
  },
  {
    id: 245,
    name: "Tonk",
    country: "India",
    attractions: ["Sunehri Kothi", "Hathi Bhata"],
  },
  {
    id: 246,
    name: "Udaipur",
    country: "India",
    attractions: ["City Palace", "Lake Pichola"],
  },
  {
    id: 247,
    name: "Alwar",
    country: "India",
    attractions: ["Bala Quila", "Sariska Tiger Reserve"],
  },
  {
    id: 248,
    name: "Bhilwara",
    country: "India",
    attractions: ["Harni Mahadev", "Mandalgarh Fort"],
  },
  {
    id: 249,
    name: "Nagaur",
    country: "India",
    attractions: ["Nagaur Fort", "Hadi Rani Mahal"],
  },
  {
    id: 250,
    name: "Pali",
    country: "India",
    attractions: ["Om Banna Temple", "Jawai Dam"],
  },
  {
    id: 251,
    name: "Balangir",
    country: "India",
    attractions: ["Harishankar Temple", "Ranipur-Jharial"],
  },
  {
    id: 252,
    name: "Balasore",
    country: "India",
    attractions: ["Chandipur Beach", "Panchalingeswar Temple"],
  },
  {
    id: 253,
    name: "Baripada",
    country: "India",
    attractions: ["Simlipal National Park", "Chandua"],
  },
  {
    id: 254,
    name: "Berhampur",
    country: "India",
    attractions: ["Taratarini Temple", "Gopalpur Beach"],
  },
  {
    id: 255,
    name: "Bhadrak",
    country: "India",
    attractions: ["Chandbali", "Akhandalamani Temple"],
  },
  {
    id: 256,
    name: "Boudh",
    country: "India",
    attractions: ["Jogindra Villa Palace", "Rameswar Temple"],
  },
  {
    id: 257,
    name: "Cuttack",
    country: "India",
    attractions: ["Barabati Fort", "Dhabaleswar Island"],
  },
  {
    id: 258,
    name: "Dhenkanal",
    country: "India",
    attractions: ["Kapilash Temple", "Saptasajya"],
  },
  {
    id: 259,
    name: "Gajapati",
    country: "India",
    attractions: ["Mahendragiri", "Khasada Waterfall"],
  },
  {
    id: 260,
    name: "Ganjam",
    country: "India",
    attractions: ["Tara Tarini Temple", "Tampara Lake"],
  },
  {
    id: 261,
    name: "Jagatsinghpur",
    country: "India",
    attractions: ["Sarala Temple", "Gada Kujanga"],
  },
  {
    id: 262,
    name: "Jajpur",
    country: "India",
    attractions: ["Biraja Temple", "Ratnagiri Monastery"],
  },
  {
    id: 263,
    name: "Jharsuguda",
    country: "India",
    attractions: ["Koilighugar Waterfall", "Ramchandi Temple"],
  },
  {
    id: 264,
    name: "Kalahandi",
    country: "India",
    attractions: ["Phurlijharan", "Karlapat Wildlife Sanctuary"],
  },
  {
    id: 265,
    name: "Kandhamal",
    country: "India",
    attractions: ["Daringbadi", "Belghar Sanctuary"],
  },
  {
    id: 266,
    name: "Kendrapara",
    country: "India",
    attractions: ["Bhitarkanika Wildlife Sanctuary", "Kendrapara"],
  },
  {
    id: 267,
    name: "Keonjhar",
    country: "India",
    attractions: ["Sanghagara Waterfall", "Gonasika"],
  },
  {
    id: 268,
    name: "Khordha",
    country: "India",
    attractions: ["Udayagiri", "Khandagiri"],
  },
  {
    id: 269,
    name: "Khordha",
    country: "India",
    attractions: ["Udayagiri", "Khandagiri"],
  },
  {
    id: 270,
    name: "Koraput",
    country: "India",
    attractions: ["Duduma Waterfall", "Jagannath Sagar"],
  },
  {
    id: 271,
    name: "Malkangiri",
    country: "India",
    attractions: ["Balimela Reservoir", "Satiguda Dam"],
  },
  {
    id: 272,
    name: "Mayurbhanj",
    country: "India",
    attractions: ["Simlipal National Park", "Barehipani Waterfall"],
  },
  {
    id: 273,
    name: "Nabarangpur",
    country: "India",
    attractions: ["Papadahandi Temple", "Podagada"],
  },
  {
    id: 274,
    name: "Nayagarh",
    country: "India",
    attractions: ["Kuanria Dam", "Satkosia Gorge"],
  },
  {
    id: 275,
    name: "Nuapada",
    country: "India",
    attractions: ["Patalganga", "Vaishnodevi Temple"],
  },
  {
    id: 276,
    name: "Rayagada",
    country: "India",
    attractions: ["Chatikona", "Paikapada Temple"],
  },
  {
    id: 277,
    name: "Sambalpur",
    country: "India",
    attractions: ["Hirakud Dam", "Samaleswari Temple"],
  },
  {
    id: 278,
    name: "Sonepur",
    country: "India",
    attractions: ["Sureswari Temple", "Swapneswar Temple"],
  },
  {
    id: 279,
    name: "Sundargarh",
    country: "India",
    attractions: ["Khandadhar Waterfall", "Mandira Dam"],
  },
  {
    id: 280,
    name: "Bastar",
    country: "India",
    attractions: ["Chitrakote Falls", "Danteshwari Temple"],
  },
  {
    id: 281,
    name: "Bilaspur",
    country: "India",
    attractions: ["Achanakmar Wildlife Sanctuary", "Malhar"],
  },
  {
    id: 282,
    name: "Durg",
    country: "India",
    attractions: ["Bhilai Steel Plant", "Maitri Bagh"],
  },
  {
    id: 283,
    name: "Jagdalpur",
    country: "India",
    attractions: ["Chitrakote Falls", "Tirathgarh Falls"],
  },
  {
    id: 284,
    name: "Korba",
    country: "India",
    attractions: ["Satrenga", "Kendai Waterfall"],
  },
  {
    id: 285,
    name: "Raigarh",
    country: "India",
    attractions: ["Ram Jharna", "Gomarda Wildlife Sanctuary"],
  },
  {
    id: 286,
    name: "Raipur",
    country: "India",
    attractions: ["Nandan Van Zoo", "Gandhi Udyan Park"],
  },
  {
    id: 287,
    name: "Rajnandgaon",
    country: "India",
    attractions: ["Ambagarh Chowki", "Dongargarh"],
  },
  {
    id: 288,
    name: "Sarguja",
    country: "India",
    attractions: ["Tamor Pingla Wildlife Sanctuary", "Mainpat"],
  },
  {
    id: 289,
    name: "Dantewada",
    country: "India",
    attractions: ["Danteshwari Temple", "Barsur"],
  },
  {
    id: 290,
    name: "Kanker",
    country: "India",
    attractions: ["Gadiya Mountain", "Kanker Palace"],
  },
  {
    id: 291,
    name: "Chamba",
    country: "India",
    attractions: ["Khajjiar", "Chamera Lake"],
  },
  {
    id: 292,
    name: "Dalhousie",
    country: "India",
    attractions: ["Panchpula", "Satdhara Falls"],
  },
  {
    id: 293,
    name: "Dharamshala",
    country: "India",
    attractions: ["McLeod Ganj", "HPCA Stadium"],
  },
  {
    id: 294,
    name: "Kangra",
    country: "India",
    attractions: ["Kangra Fort", "Masroor Rock Cut Temple"],
  },
  {
    id: 295,
    name: "Kasauli",
    country: "India",
    attractions: ["Monkey Point", "Christ Church"],
  },
  {
    id: 296,
    name: "Kinnaur",
    country: "India",
    attractions: ["Sangla Valley", "Chitkul"],
  },
  {
    id: 297,
    name: "Kullu",
    country: "India",
    attractions: ["Great Himalayan National Park", "Bijli Mahadev Temple"],
  },
  {
    id: 298,
    name: "Lahaul and Spiti",
    country: "India",
    attractions: ["Key Monastery", "Pin Valley National Park"],
  },
  {
    id: 299,
    name: "Mandi",
    country: "India",
    attractions: ["Rewalsar Lake", "Prashar Lake"],
  },
  {
    id: 300,
    name: "Shimla",
    country: "India",
    attractions: ["The Ridge", "Mall Road"],
  },
  {
    id: 301,
    name: "Solan",
    country: "India",
    attractions: ["Mohan Shakti National Heritage Park", "Kasauli Brewery"],
  },
  {
    id: 302,
    name: "Bilaspur",
    country: "India",
    attractions: ["Gobind Sagar Lake", "Bhakra Dam"],
  },
  {
    id: 303,
    name: "Hamirpur",
    country: "India",
    attractions: ["Sujanpur Tira", "Deotsidh Temple"],
  },
  {
    id: 304,
    name: "Una",
    country: "India",
    attractions: ["Chintpurni Temple", "Dera Baba Bharbhag Singh"],
  },
  {
    id: 305,
    name: "Sirmaur",
    country: "India",
    attractions: ["Renuka Lake", "Churdhar"],
  },
  {
    id: 306,
    name: "Kargil",
    country: "India",
    attractions: ["Drass War Memorial", "Mulbekh Monastery"],
  },
  {
    id: 307,
    name: "Leh",
    country: "India",
    attractions: ["Shanti Stupa", "Leh Palace"],
  },
  {
    id: 308,
    name: "Srinagar",
    country: "India",
    attractions: ["Dal Lake", "Mughal Gardens"],
  },
  {
    id: 309,
    name: "Anantnag",
    country: "India",
    attractions: ["Martand Sun Temple", "Kokernag"],
  },
  {
    id: 310,
    name: "Baramulla",
    country: "India",
    attractions: ["Gulmarg", "Baramulla Museum"],
  },
  {
    id: 311,
    name: "Pulwama",
    country: "India",
    attractions: ["Awantipora Ruins", "Tarsar Lake"],
  },
  {
    id: 312,
    name: "Pahalgam",
    country: "India",
    attractions: ["Betaab Valley", "Aru Valley"],
  },
  {
    id: 313,
    name: "Katra",
    country: "India",
    attractions: ["Vaishno Devi Temple", "Bhimgarh Fort"],
  },
  {
    id: 314,
    name: "Patnitop",
    country: "India",
    attractions: ["Nathatop", "Madhatop"],
  },
  {
    id: 315,
    name: "Udhampur",
    country: "India",
    attractions: ["Krimchi Temples", "Ramnagar Fort"],
  },
  {
    id: 316,
    name: "Jammu",
    country: "India",
    attractions: ["Raghunath Temple", "Amar Mahal Palace"],
  },
  {
    id: 317,
    name: "Kupwara",
    country: "India",
    attractions: ["Lolab Valley", "Bangus Valley"],
  },
  {
    id: 318,
    name: "Doda",
    country: "India",
    attractions: ["Bhaderwah", "Kishtwar National Park"],
  },
  {
    id: 319,
    name: "Kishtwar",
    country: "India",
    attractions: ["Sinthan Top", "Machail Mata"],
  },
  {
    id: 320,
    name: "Rajouri",
    country: "India",
    attractions: ["Dera Ki Gali", "Thanamandi"],
  },
  {
    id: 321,
    name: "Reasi",
    country: "India",
    attractions: ["Shivkhori", "Bhimgarh Fort"],
  },
  {
    id: 322,
    name: "Poonch",
    country: "India",
    attractions: ["Noori Chamb", "Peer Ki Gali"],
  },
  {
    id: 323,
    name: "Kulgam",
    country: "India",
    attractions: ["Aharbal Waterfall", "Verinag Spring"],
  },
  {
    id: 324,
    name: "Shopian",
    country: "India",
    attractions: ["Dobjan", "Hirpora Wildlife Sanctuary"],
  },
  {
    id: 325,
    name: "Bandipora",
    country: "India",
    attractions: ["Wular Lake", "Gurez Valley"],
  },
  {
    id: 326,
    name: "Nashik",
    country: "India",
    attractions: ["Trimbakeshwar Temple", "Sula Vineyards"],
  },
  {
    id: 327,
    name: "Shrirampur",
    country: "India",
    attractions: ["Pravara River", "Pravara Nagar"],
  },
  {
    id: 328,
    name: "Aurangabad",
    country: "India",
    attractions: ["Ajanta Caves", "Ellora Caves"],
  },
  {
    id: 329,
    name: "Lonavala",
    country: "India",
    attractions: ["Lion’s Point", "Karla Caves"],
  },
  {
    id: 330,
    name: "Pune",
    country: "India",
    attractions: ["Shaniwar Wada", "Aga Khan Palace"],
  },
  {
    id: 331,
    name: "Shirdi",
    country: "India",
    attractions: ["Sai Baba Temple", "Shani Shingnapur"],
  },
  {
    id: 332,
    name: "Mahabaleshwar",
    country: "India",
    attractions: ["Arthur’s Seat", "Venna Lake"],
  },
  {
    id: 333,
    name: "Alibaug",
    country: "India",
    attractions: ["Alibaug Beach", "Kolaba Fort"],
  },
  {
    id: 334,
    name: "Kolhapur",
    country: "India",
    attractions: ["Mahalaxmi Temple", "Panhala Fort"],
  },
  {
    id: 335,
    name: "Ratnagiri",
    country: "India",
    attractions: ["Ganpatipule Beach", "Jaigad Fort"],
  },
  {
    id: 336,
    name: "Nagpur",
    country: "India",
    attractions: ["Deekshabhoomi", "Futala Lake"],
  },
  {
    id: 337,
    name: "Sindhudurg",
    country: "India",
    attractions: ["Sindhudurg Fort", "Tarkarli Beach"],
  },
  {
    id: 338,
    name: "Chandrapur",
    country: "India",
    attractions: ["Tadoba Andhari Tiger Reserve", "Chandrapur Fort"],
  },
  {
    id: 339,
    name: "Nanded",
    country: "India",
    attractions: ["Hazur Sahib", "Nanded Fort"],
  },
  {
    id: 340,
    name: "Solapur",
    country: "India",
    attractions: ["Solapur Fort", "Siddheshwar Temple"],
  },
  {
    id: 341,
    name: "Amravati",
    country: "India",
    attractions: ["Chikhaldara Wildlife Sanctuary", "Gugamal National Park"],
  },
  {
    id: 342,
    name: "Akola",
    country: "India",
    attractions: ["Raj Rajeshwar Temple", "Narnala Fort"],
  },
  {
    id: 343,
    name: "Bhandara",
    country: "India",
    attractions: ["Andhalgaon", "Ambagarh Fort"],
  },
  {
    id: 344,
    name: "Beed",
    country: "India",
    attractions: ["Kankaleshwar Temple", "Parli Vaijnath Temple"],
  },
  {
    id: 345,
    name: "Nashik",
    country: "India",
    attractions: ["Sula Vineyards", "Pandavleni Caves"],
  },
  {
    id: 346,
    name: "Jalgaon",
    country: "India",
    attractions: ["Ajanta Caves", "Patna Devi"],
  },
  {
    id: 347,
    name: "Satara",
    country: "India",
    attractions: ["Kaas Plateau", "Thoseghar Waterfalls"],
  },
  {
    id: 348,
    name: "Aurangabad",
    country: "India",
    attractions: ["Bibi Ka Maqbara", "Daulatabad Fort"],
  },
  {
    id: 349,
    name: "Gondia",
    country: "India",
    attractions: ["Navegaon National Park", "Itiadoh Dam"],
  },
  {
    id: 350,
    name: "Gadchiroli",
    country: "India",
    attractions: ["Bhamragarh Wildlife Sanctuary", "Vairagad Fort"],
  },
  {
    id: 351,
    name: "Dhule",
    country: "India",
    attractions: ["Laling Fort", "Songir Fort"],
  },
  {
    id: 352,
    name: "Nandurbar",
    country: "India",
    attractions: ["Toranmal", "Asthamba"],
  },
  {
    id: 353,
    name: "Parbhani",
    country: "India",
    attractions: ["Jintur Jain Temple", "Mudgaleshwar Temple"],
  },
  {
    id: 354,
    name: "Hingoli",
    country: "India",
    attractions: ["Aundha Nagnath Temple", "Mallinath Digambar Jain Temple"],
  },
  {
    id: 355,
    name: "Latur",
    country: "India",
    attractions: ["Udgir Fort", "Kharosa Caves"],
  },
  {
    id: 356,
    name: "Osmanabad",
    country: "India",
    attractions: ["Tuljapur Temple", "Dharashiv Caves"],
  },
  {
    id: 357,
    name: "Yavatmal",
    country: "India",
    attractions: ["Tipeshwar Wildlife Sanctuary", "Mahur Fort"],
  },
  {
    id: 358,
    name: "Washim",
    country: "India",
    attractions: ["Balaji Temple", "Antariksh Parshwanath Jain Mandir"],
  },
  {
    id: 359,
    name: "Wardha",
    country: "India",
    attractions: ["Sevagram Ashram", "Laxmi Narayan Temple"],
  },
  {
    id: 360,
    name: "Hinganghat",
    country: "India",
    attractions: ["Sant Namdev Temple", "Hinganghat Fort"],
  },
  {
    id: 361,
    name: "Buldhana",
    country: "India",
    attractions: ["Lonar Lake", "Sindkhed Raja"],
  },
  {
    id: 362,
    name: "Ahmednagar",
    country: "India",
    attractions: ["Shirdi", "Ahmednagar Fort"],
  },
  {
    id: 363,
    name: "Pandharpur",
    country: "India",
    attractions: ["Vitthal Temple", "Pundalik Temple"],
  },
  {
    id: 364,
    name: "Sangli",
    country: "India",
    attractions: ["Ganapati Temple", "Sangli Fort"],
  },
  {
    id: 365,
    name: "Kolhapur",
    country: "India",
    attractions: ["Mahalaxmi Temple", "Rankala Lake"],
  },
  {
    id: 366,
    name: "Ratnagiri",
    country: "India",
    attractions: ["Ganpatipule Beach", "Jaigad Fort"],
  },
  {
    id: 367,
    name: "Nashik",
    country: "India",
    attractions: ["Sula Vineyards", "Pandavleni Caves"],
  },
  {
    id: 368,
    name: "Jalgaon",
    country: "India",
    attractions: ["Ajanta Caves", "Patna Devi"],
  },
  {
    id: 369,
    name: "Satara",
    country: "India",
    attractions: ["Kaas Plateau", "Thoseghar Waterfalls"],
  },
  {
    id: 370,
    name: "Aurangabad",
    country: "India",
    attractions: ["Bibi Ka Maqbara", "Daulatabad Fort"],
  },
  {
    id: 371,
    name: "Gondia",
    country: "India",
    attractions: ["Navegaon National Park", "Itiadoh Dam"],
  },
  {
    id: 372,
    name: "Gadchiroli",
    country: "India",
    attractions: ["Bhamragarh Wildlife Sanctuary", "Vairagad Fort"],
  },
  {
    id: 373,
    name: "Dhule",
    country: "India",
    attractions: ["Laling Fort", "Songir Fort"],
  },
  {
    id: 374,
    name: "Nandurbar",
    country: "India",
    attractions: ["Toranmal", "Asthamba"],
  },
  {
    id: 375,
    name: "Parbhani",
    country: "India",
    attractions: ["Jintur Jain Temple", "Mudgaleshwar Temple"],
  },
  {
    id: 376,
    name: "Hingoli",
    country: "India",
    attractions: ["Aundha Nagnath Temple", "Mallinath Digambar Jain Temple"],
  },
  {
    id: 377,
    name: "Latur",
    country: "India",
    attractions: ["Udgir Fort", "Kharosa Caves"],
  },
  {
    id: 378,
    name: "Osmanabad",
    country: "India",
    attractions: ["Tuljapur Temple", "Dharashiv Caves"],
  },
  {
    id: 379,
    name: "Yavatmal",
    country: "India",
    attractions: ["Tipeshwar Wildlife Sanctuary", "Mahur Fort"],
  },
  {
    id: 380,
    name: "Washim",
    country: "India",
    attractions: ["Balaji Temple", "Antariksh Parshwanath Jain Mandir"],
  },
  {
    id: 381,
    name: "Wardha",
    country: "India",
    attractions: ["Sevagram Ashram", "Laxmi Narayan Temple"],
  },
  {
    id: 382,
    name: "Hinganghat",
    country: "India",
    attractions: ["Sant Namdev Temple", "Hinganghat Fort"],
  },
  {
    id: 383,
    name: "Buldhana",
    country: "India",
    attractions: ["Lonar Lake", "Sindkhed Raja"],
  },
  {
    id: 384,
    name: "Ahmednagar",
    country: "India",
    attractions: ["Shirdi", "Ahmednagar Fort"],
  },
  {
    id: 385,
    name: "Pandharpur",
    country: "India",
    attractions: ["Vitthal Temple", "Pundalik Temple"],
  },
  {
    id: 386,
    name: "Sangli",
    country: "India",
    attractions: ["Ganapati Temple", "Sangli Fort"],
  },
  {
    id: 387,
    name: "Jalgaon",
    country: "India",
    attractions: ["Patna Devi", "Ajanta Caves"],
  },
  {
    id: 388,
    name: "Satara",
    country: "India",
    attractions: ["Kaas Plateau", "Thoseghar Waterfalls"],
  },
  {
    id: 389,
    name: "Aurangabad",
    country: "India",
    attractions: ["Bibi Ka Maqbara", "Daulatabad Fort"],
  },
  {
    id: 390,
    name: "Gondia",
    country: "India",
    attractions: ["Navegaon National Park", "Itiadoh Dam"],
  },
  {
    id: 391,
    name: "Gadchiroli",
    country: "India",
    attractions: ["Bhamragarh Wildlife Sanctuary", "Vairagad Fort"],
  },
  {
    id: 392,
    name: "Dhule",
    country: "India",
    attractions: ["Laling Fort", "Songir Fort"],
  },
  {
    id: 393,
    name: "Nandurbar",
    country: "India",
    attractions: ["Toranmal", "Asthamba"],
  },
  {
    id: 394,
    name: "Parbhani",
    country: "India",
    attractions: ["Jintur Jain Temple", "Mudgaleshwar Temple"],
  },
  {
    id: 395,
    name: "Hingoli",
    country: "India",
    attractions: ["Aundha Nagnath Temple", "Mallinath Digambar Jain Temple"],
  },
  {
    id: 396,
    name: "Latur",
    country: "India",
    attractions: ["Udgir Fort", "Kharosa Caves"],
  },
  {
    id: 397,
    name: "Osmanabad",
    country: "India",
    attractions: ["Tuljapur Temple", "Dharashiv Caves"],
  },
  {
    id: 398,
    name: "Yavatmal",
    country: "India",
    attractions: ["Tipeshwar Wildlife Sanctuary", "Mahur Fort"],
  },
  {
    id: 399,
    name: "Washim",
    country: "India",
    attractions: ["Balaji Temple", "Antariksh Parshwanath Jain Mandir"],
  },
  {
    id: 400,
    name: "Wardha",
    country: "India",
    attractions: ["Sevagram Ashram", "Laxmi Narayan Temple"],
  },
  {
    id: 401,
    name: "Hinganghat",
    country: "India",
    attractions: ["Sant Namdev Temple", "Hinganghat Fort"],
  },
  {
    id: 402,
    name: "Buldhana",
    country: "India",
    attractions: ["Lonar Lake", "Sindkhed Raja"],
  },
  {
    id: 403,
    name: "Ahmednagar",
    country: "India",
    attractions: ["Shirdi", "Ahmednagar Fort"],
  },
  {
    id: 404,
    name: "Pandharpur",
    country: "India",
    attractions: ["Vitthal Temple", "Pundalik Temple"],
  },
  {
    id: 405,
    name: "Sangli",
    country: "India",
    attractions: ["Ganapati Temple", "Sangli Fort"],
  },
  {
    id: 406,
    name: "Nashik",
    country: "India",
    attractions: ["Sula Vineyards", "Pandavleni Caves"],
  },
  {
    id: 407,
    name: "Jalgaon",
    country: "India",
    attractions: ["Ajanta Caves", "Patna Devi"],
  },
  {
    id: 408,
    name: "Satara",
    country: "India",
    attractions: ["Kaas Plateau", "Thoseghar Waterfalls"],
  },
  {
    id: 409,
    name: "Aurangabad",
    country: "India",
    attractions: ["Bibi Ka Maqbara", "Daulatabad Fort"],
  },
  {
    id: 410,
    name: "Gondia",
    country: "India",
    attractions: ["Navegaon National Park", "Itiadoh Dam"],
  },
  {
    id: 411,
    name: "Gadchiroli",
    country: "India",
    attractions: ["Bhamragarh Wildlife Sanctuary", "Vairagad Fort"],
  },
  {
    id: 412,
    name: "Dhule",
    country: "India",
    attractions: ["Laling Fort", "Songir Fort"],
  },
  {
    id: 413,
    name: "Nandurbar",
    country: "India",
    attractions: ["Toranmal", "Asthamba"],
  },
  {
    id: 414,
    name: "Parbhani",
    country: "India",
    attractions: ["Jintur Jain Temple", "Mudgaleshwar Temple"],
  },
  {
    id: 415,
    name: "Hingoli",
    country: "India",
    attractions: ["Aundha Nagnath Temple", "Mallinath Digambar Jain Temple"],
  },
  {
    id: 416,
    name: "Latur",
    country: "India",
    attractions: ["Udgir Fort", "Kharosa Caves"],
  },
  {
    id: 417,
    name: "Osmanabad",
    country: "India",
    attractions: ["Tuljapur Temple", "Dharashiv Caves"],
  },
  {
    id: 418,
    name: "Yavatmal",
    country: "India",
    attractions: ["Tipeshwar Wildlife Sanctuary", "Mahur Fort"],
  },
  {
    id: 419,
    name: "Washim",
    country: "India",
    attractions: ["Balaji Temple", "Antariksh Parshwanath Jain Mandir"],
  },
  {
    id: 420,
    name: "Wardha",
    country: "India",
    attractions: ["Sevagram Ashram", "Laxmi Narayan Temple"],
  },
  {
    id: 421,
    name: "Hinganghat",
    country: "India",
    attractions: ["Sant Namdev Temple", "Hinganghat Fort"],
  },
  {
    id: 422,
    name: "Buldhana",
    country: "India",
    attractions: ["Lonar Lake", "Sindkhed Raja"],
  },
  {
    id: 423,
    name: "Ahmednagar",
    country: "India",
    attractions: ["Shirdi", "Ahmednagar Fort"],
  },
  {
    id: 424,
    name: "Pandharpur",
    country: "India",
    attractions: ["Vitthal Temple", "Pundalik Temple"],
  },
  {
    id: 425,
    name: "Sangli",
    country: "India",
    attractions: ["Ganapati Temple", "Sangli Fort"],
  },
  {
    id: 426,
    name: "Nashik",
    country: "India",
    attractions: ["Sula Vineyards", "Pandavleni Caves"],
  },
  {
    id: 427,
    name: "Jalgaon",
    country: "India",
    attractions: ["Ajanta Caves", "Patna Devi"],
  },
  {
    id: 428,
    name: "Satara",
    country: "India",
    attractions: ["Kaas Plateau", "Thoseghar Waterfalls"],
  },
  {
    id: 429,
    name: "Aurangabad",
    country: "India",
    attractions: ["Bibi Ka Maqbara", "Daulatabad Fort"],
  },
  {
    id: 430,
    name: "Gondia",
    country: "India",
    attractions: ["Navegaon National Park", "Itiadoh Dam"],
  },
  {
    id: 431,
    name: "Gadchiroli",
    country: "India",
    attractions: ["Bhamragarh Wildlife Sanctuary", "Vairagad Fort"],
  },
  {
    id: 432,
    name: "Dhule",
    country: "India",
    attractions: ["Laling Fort", "Songir Fort"],
  },
  {
    id: 433,
    name: "Nandurbar",
    country: "India",
    attractions: ["Toranmal", "Asthamba"],
  },
  {
    id: 434,
    name: "Parbhani",
    country: "India",
    attractions: ["Jintur Jain Temple", "Mudgaleshwar Temple"],
  },
  {
    id: 435,
    name: "Hingoli",
    country: "India",
    attractions: ["Aundha Nagnath Temple", "Mallinath Digambar Jain Temple"],
  },
  {
    id: 436,
    name: "Latur",
    country: "India",
    attractions: ["Udgir Fort", "Kharosa Caves"],
  },
  {
    id: 437,
    name: "Osmanabad",
    country: "India",
    attractions: ["Tuljapur Temple", "Dharashiv Caves"],
  },
  {
    id: 438,
    name: "Yavatmal",
    country: "India",
    attractions: ["Tipeshwar Wildlife Sanctuary", "Mahur Fort"],
  },
  {
    id: 439,
    name: "Washim",
    country: "India",
    attractions: ["Balaji Temple", "Antariksh Parshwanath Jain Mandir"],
  },
  {
    id: 440,
    name: "Wardha",
    country: "India",
    attractions: ["Sevagram Ashram", "Laxmi Narayan Temple"],
  },
  {
    id: 441,
    name: "Hinganghat",
    country: "India",
    attractions: ["Sant Namdev Temple", "Hinganghat Fort"],
  },
  {
    id: 442,
    name: "Buldhana",
    country: "India",
    attractions: ["Lonar Lake", "Sindkhed Raja"],
  },
  {
    id: 443,
    name: "Ahmednagar",
    country: "India",
    attractions: ["Shirdi", "Ahmednagar Fort"],
  },
  {
    id: 444,
    name: "Pandharpur",
    country: "India",
    attractions: ["Vitthal Temple", "Pundalik Temple"],
  },
  {
    id: 445,
    name: "Sangli",
    country: "India",
    attractions: ["Ganapati Temple", "Sangli Fort"],
  },
  {
    id: 446,
    name: "Nashik",
    country: "India",
    attractions: ["Sula Vineyards", "Pandavleni Caves"],
  },
  {
    id: 447,
    name: "Jalgaon",
    country: "India",
    attractions: ["Ajanta Caves", "Patna Devi"],
  },
  {
    id: 448,
    name: "Satara",
    country: "India",
    attractions: ["Kaas Plateau", "Thoseghar Waterfalls"],
  },
  {
    id: 449,
    name: "Aurangabad",
    country: "India",
    attractions: ["Bibi Ka Maqbara", "Daulatabad Fort"],
  },
  {
    id: 450,
    name: "Gondia",
    country: "India",
    attractions: ["Navegaon National Park", "Itiadoh Dam"],
  },
  {
    id: 451,
    name: "Gadchiroli",
    country: "India",
    attractions: ["Bhamragarh Wildlife Sanctuary", "Vairagad Fort"],
  },
  {
    id: 452,
    name: "Dhule",
    country: "India",
    attractions: ["Laling Fort", "Songir Fort"],
  },
  {
    id: 453,
    name: "Nandurbar",
    country: "India",
    attractions: ["Toranmal", "Asthamba"],
  },
  {
    id: 454,
    name: "Parbhani",
    country: "India",
    attractions: ["Jintur Jain Temple", "Mudgaleshwar Temple"],
  },
  {
    id: 455,
    name: "Hingoli",
    country: "India",
    attractions: ["Aundha Nagnath Temple", "Mallinath Digambar Jain Temple"],
  },
  {
    id: 456,
    name: "Latur",
    country: "India",
    attractions: ["Udgir Fort", "Kharosa Caves"],
  },
  {
    id: 457,
    name: "Osmanabad",
    country: "India",
    attractions: ["Tuljapur Temple", "Dharashiv Caves"],
  },
  {
    id: 458,
    name: "Yavatmal",
    country: "India",
    attractions: ["Tipeshwar Wildlife Sanctuary", "Mahur Fort"],
  },
  {
    id: 459,
    name: "Washim",
    country: "India",
    attractions: ["Balaji Temple", "Antariksh Parshwanath Jain Mandir"],
  },
  {
    id: 460,
    name: "Wardha",
    country: "India",
    attractions: ["Sevagram Ashram", "Laxmi Narayan Temple"],
  },
  {
    id: 461,
    name: "Hinganghat",
    country: "India",
    attractions: ["Sant Namdev Temple", "Hinganghat Fort"],
  },
  {
    id: 462,
    name: "Buldhana",
    country: "India",
    attractions: ["Lonar Lake", "Sindkhed Raja"],
  },
  {
    id: 463,
    name: "Ahmednagar",
    country: "India",
    attractions: ["Shirdi", "Ahmednagar Fort"],
  },
  {
    id: 464,
    name: "Pandharpur",
    country: "India",
    attractions: ["Vitthal Temple", "Pundalik Temple"],
  },
  {
    id: 465,
    name: "Sangli",
    country: "India",
    attractions: ["Ganapati Temple", "Sangli Fort"],
  },
  {
    id: 466,
    name: "Nashik",
    country: "India",
    attractions: ["Sula Vineyards", "Pandavleni Caves"],
  },
  {
    id: 467,
    name: "Jalgaon",
    country: "India",
    attractions: ["Ajanta Caves", "Patna Devi"],
  },
  {
    id: 468,
    name: "Satara",
    country: "India",
    attractions: ["Kaas Plateau", "Thoseghar Waterfalls"],
  },
  {
    id: 469,
    name: "Aurangabad",
    country: "India",
    attractions: ["Bibi Ka Maqbara", "Daulatabad Fort"],
  },
  {
    id: 470,
    name: "Gondia",
    country: "India",
    attractions: ["Navegaon National Park", "Itiadoh Dam"],
  },
  {
    id: 471,
    name: "Gadchiroli",
    country: "India",
    attractions: ["Bhamragarh Wildlife Sanctuary", "Vairagad Fort"],
  },
  {
    id: 472,
    name: "Dhule",
    country: "India",
    attractions: ["Laling Fort", "Songir Fort"],
  },
  {
    id: 473,
    name: "Nandurbar",
    country: "India",
    attractions: ["Toranmal", "Asthamba"],
  },
  {
    id: 474,
    name: "Parbhani",
    country: "India",
    attractions: ["Jintur Jain Temple", "Mudgaleshwar Temple"],
  },
  {
    id: 475,
    name: "Hingoli",
    country: "India",
    attractions: ["Aundha Nagnath Temple", "Mallinath Digambar Jain Temple"],
  },
  {
    id: 476,
    name: "Latur",
    country: "India",
    attractions: ["Udgir Fort", "Kharosa Caves"],
  },
  {
    id: 477,
    name: "Osmanabad",
    country: "India",
    attractions: ["Tuljapur Temple", "Dharashiv Caves"],
  },
  {
    id: 478,
    name: "Yavatmal",
    country: "India",
    attractions: ["Tipeshwar Wildlife Sanctuary", "Mahur Fort"],
  },
  {
    id: 479,
    name: "Washim",
    country: "India",
    attractions: ["Balaji Temple", "Antariksh Parshwanath Jain Mandir"],
  },
  {
    id: 480,
    name: "Wardha",
    country: "India",
    attractions: ["Sevagram Ashram", "Laxmi Narayan Temple"],
  },
  {
    id: 481,
    name: "Hinganghat",
    country: "India",
    attractions: ["Sant Namdev Temple", "Hinganghat Fort"],
  },
  {
    id: 482,
    name: "Buldhana",
    country: "India",
    attractions: ["Lonar Lake", "Sindkhed Raja"],
  },
  {
    id: 483,
    name: "Ahmednagar",
    country: "India",
    attractions: ["Shirdi", "Ahmednagar Fort"],
  },
  {
    id: 484,
    name: "Pandharpur",
    country: "India",
    attractions: ["Vitthal Temple", "Pundalik Temple"],
  },
  {
    id: 485,
    name: "Sangli",
    country: "India",
    attractions: ["Ganapati Temple", "Sangli Fort"],
  },
  {
    id: 486,
    name: "Nashik",
    country: "India",
    attractions: ["Sula Vineyards", "Pandavleni Caves"],
  },
  {
    id: 487,
    name: "Jalgaon",
    country: "India",
    attractions: ["Ajanta Caves", "Patna Devi"],
  },
  {
    id: 488,
    name: "Satara",
    country: "India",
    attractions: ["Kaas Plateau", "Thoseghar Waterfalls"],
  },
  {
    id: 489,
    name: "Aurangabad",
    country: "India",
    attractions: ["Bibi Ka Maqbara", "Daulatabad Fort"],
  },
  {
    id: 490,
    name: "Gondia",
    country: "India",
    attractions: ["Navegaon National Park", "Itiadoh Dam"],
  },
  {
    id: 491,
    name: "Gadchiroli",
    country: "India",
    attractions: ["Bhamragarh Wildlife Sanctuary", "Vairagad Fort"],
  },
  {
    id: 492,
    name: "Dhule",
    country: "India",
    attractions: ["Laling Fort", "Songir Fort"],
  },
  {
    id: 493,
    name: "Nandurbar",
    country: "India",
    attractions: ["Toranmal", "Asthamba"],
  },
  {
    id: 494,
    name: "Parbhani",
    country: "India",
    attractions: ["Jintur Jain Temple", "Mudgaleshwar Temple"],
  },
  {
    id: 495,
    name: "Hingoli",
    country: "India",
    attractions: ["Aundha Nagnath Temple", "Mallinath Digambar Jain Temple"],
  },
  {
    id: 496,
    name: "Latur",
    country: "India",
    attractions: ["Udgir Fort", "Kharosa Caves"],
  },
  {
    id: 497,
    name: "Osmanabad",
    country: "India",
    attractions: ["Tuljapur Temple", "Dharashiv Caves"],
  },
  {
    id: 498,
    name: "Yavatmal",
    country: "India",
    attractions: ["Tipeshwar Wildlife Sanctuary", "Mahur Fort"],
  },
  {
    id: 499,
    name: "Washim",
    country: "India",
    attractions: ["Balaji Temple", "Antariksh Parshwanath Jain Mandir"],
  },
  {
    id: 500,
    name: "Wardha",
    country: "India",
    attractions: ["Sevagram Ashram", "Laxmi Narayan Temple"],
  },
];

router.get("/", (req, res) => {
  res.json(destinations);
});

module.exports = router;
